### ISSUE TITLE
Support Channel Sending

### ISSUE THREAD

**Issue by Artucuno** [interactions-py/files#25]
Hey, how do I send files to channels that aren't a part of the ctx?

EG:
```py
channel = await interactions.get(self.bot, interactions.Channel, object_id=00000)
await command_send(channel, "Test", files=file, embeds=[embed], ephemeral=True)
```

Thanks!

**Comment by mAxYoLo01** [comment]
Hello, it's as simple as getting the channel and sending files using `await channel.send(files=...)`. No need to use this library if it's to send files outside of Context. Please use the #help channel on the Discord server in the future for questions like these.

**Comment by Artucuno** [comment]
Thanks!
