### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by macqueen0987** [interactions-py/files#26]
Do you have plans for updating this for latest versoin of interactions?

**Comment by B1ue-Dev** [comment]
Oh hey! Yes, `files` will be updated to support the latest version of interactions.py soon, just not today, since I am extremely busy with my current schedule, which mostly related to study and work. My apologize if my busy affects your bot when using my extension.

**Comment by macqueen0987** [comment]
nope just greatfull for creating this extension... thanks for answering

**Comment by sillyElvy** [comment]
> Do you have plans for updating this for latest versoin of interactions?

We even plan on integrating it into the main library atm ^^
